topolvm controller certs management
alauda/topolvm-operator pull request #76
Opened 2021-11-18 09:54 UTC by jmolmo

Implements: #62

I have included a new parameter in the cluster CRD for providing the name of the secret containing the certificate that will be used by topolvm-controller mutation webhook.
This will allow the user to  us cert-manager to create the certificate, o any other certificate provision, only is required to create a TLS secret with the certificate and the key.

In case that the user does not provide the CRD `certsSecret` parameter, a self signed certificate will be created automatically and used in topolvm-controller deployment.
This also happens if the user has provided the parameter `certsSecret` , but using a wrng name, or if the secret does not exists in the topolvm namespace.

After discussion, more work needed to add the new parameter in the Helm chart, add documentation, and test.

2021-11-18 10:22 UTC, little-guy-lxr commented
@jmolmo thanks for your contribution.  I think that your PR is ok, Do you have any other concerns you need to discuss? if not， I will merge it.

2021-11-18 10:50 UTC, jmolmo commented
> @jmolmo thanks for your contribution. I think that your PR is ok, Do you have any other concerns you need to discuss? if not， I will merge it.
@little-guy-lxr : thx for your revision. Nothing to discuss from my part. But let me add the documentation and the changes in the helm charts.

2021-11-18 11:01 UTC, sp98 requested changes
nit

2021-11-18 11:18 UTC, sp98 requested changes

2021-11-18 11:18 UTC, sp98 commented on pkg/operator/volumectr/volume_controller.go
> +				logger.Errorf("Self signed certificate will be used. Unexpected error trying to locate secret '%s': %s", cluster.CertsSecret, err)
```suggestion
				logger.Errorf("Self signed certificate will be used. Unexpected error trying to locate secret %q': %v", cluster.CertsSecret, err)
```
To add quotes.

2021-11-18 11:18 UTC, sp98 commented on pkg/operator/volumectr/volume_controller.go
> +				logger.Errorf("Self signed certificate will be used. Unexpected error trying to locate secret '%s': %s", cluster.CertsSecret, err)
Why not throw error if user has enabled certs but not provided any ?

2021-11-19 04:13 UTC, sp98 commented
LGTM

2021-11-19 06:37 UTC, merged